apiVersion: apps/v1
kind: Deployment
metadata:
  name: server  # Nome do Deployment
spec:
  selector:
    matchLabels:
      app: server  # O seletor para os Pods gerenciados por este Deployment
  template:
    metadata:
      labels:
        app: server  # O label atribuído aos Pods gerenciados por este Deployment
    spec:
      serviceAccount: server  # ServiceAccount a ser usado pelos Pods deste Deployment
      containers:
      - name: server
        image: pedrohca/kube-go
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
