apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "pedrohca/kube-go:v7.5"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 1

          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 80
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   timeoutSeconds: 20
          #   successThreshold: 1
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/myTasks"
              name: config

      volumes:
        - name: config
          configMap:
            name: configmap-task
            items:
            - key: tasks
              path: "task.txt"  
